version: '3'

services:

  jenkins:
    image: n1c0l4stournier/jenkins:2.138.1-alpine
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - jenkins-data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
